const API = '/api';
const state = {bootstrap:null, overview:null, assets:[], findings:[], jobs:[], reports:[], integrations:[], compliance:null, aiActions:[], securityEvents:[], securityMonitoring:null, realtimeMonitoringAllowed:false, latestSecurityEventId:0, currentView:'overview', currentFinding:null, monitoringTimer:null, lastRefreshAt:null, onboarding:{step:1,domain:'',cloud:'',github:'later',employees:''}};
const labels = {overview:'Visão Geral',assets:'Ativos',risks:'Riscos',monitoring:'Monitoramento',reports:'Relatórios',compliance:'Conformidade',ai:'Iron AI',integrations:'Integrações',settings:'Configurações'};
const actionLabels = {asset_created:'Ativo adicionado',findings_reconciled:'Scans importados',finding_status_changed:'Status de risco alterado',report_generated:'Relatório gerado',integration_connected:'Integração conectada',integration_synced:'Integração sincronizada',ai_action_proposed:'Ação proposta pela Iron AI',ai_action_approved:'Ação da IA aprovada',ai_action_executed:'Ação da IA executada',job_queued:'Job adicionado à fila',organization_updated:'Organização atualizada',compliance_control_updated:'Controle de conformidade atualizado'};

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const token = () => localStorage.getItem('access_token') || sessionStorage.getItem('access_token') || localStorage.getItem('token') || sessionStorage.getItem('token');
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const dateLabel = value => value ? new Date(value).toLocaleString('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}) : '—';
const severityLabel = value => ({critical:'Crítico',high:'Alto',medium:'Médio',low:'Baixo',informational:'Informativo'}[value] || value || 'Médio');
const statusLabel = value => ({not_started:'Não iniciado',open:'Aberto',in_progress:'Em andamento',implemented:'Implementado',accepted_risk:'Risco aceito',resolved:'Resolvido',false_positive:'Falso positivo',queued:'Na fila',running:'Executando',completed:'Concluído',failed:'Falhou',proposed:'Aguardando aprovação',approved:'Aprovada',rejected:'Rejeitada',executed:'Executada'}[value] || value || '—');

async function api(path, options={}) {
  const headers = {...(options.headers || {})};
  if (token()) headers.Authorization = `Bearer ${token()}`;
  if (options.body && !(options.body instanceof FormData)) headers['Content-Type'] = 'application/json';
  let response = await fetch(`${API}${path}`, {...options, headers});
  if (response.status === 402) {
    clearSession();
    location.href='/index.html?renewal_required=true';
    throw new Error('Seu período de acesso terminou. Entre novamente para renovar.');
  }
  if (response.status === 401 && !options._retried && token()) {
    const refreshed = await fetch(`${API}/auth/refresh`, {method:'POST',headers:{Authorization:`Bearer ${token()}`}});
    if (refreshed.ok) {
      const data = await refreshed.json();
      localStorage.setItem('access_token', data.access_token);
      return api(path, {...options,_retried:true});
    }
    clearSession();
    location.href='/index.html';
    throw new Error('Sua sessão expirou. Entre novamente.');
  }
  const contentType = response.headers.get('content-type') || '';
  const data = contentType.includes('application/json') ? await response.json() : await response.text();
  if (!response.ok) {
    const detail = data?.detail;
    throw new Error(typeof detail === 'string' ? detail : detail?.message || data?.message || `Erro ${response.status}`);
  }
  return data;
}

function clearSession(){['access_token','token','username'].forEach(k=>localStorage.removeItem(k));['access_token','token'].forEach(k=>sessionStorage.removeItem(k));}
function toast(message,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<i class="fa-solid ${type==='error'?'fa-circle-exclamation':'fa-circle-check'}"></i><span>${escapeHtml(message)}</span>`;$('#toast-container').appendChild(el);setTimeout(()=>el.remove(),4200)}
function setBusy(button,busy,text='Processando...'){if(!button)return;if(busy){button.dataset.original=button.innerHTML;button.disabled=true;button.innerHTML=`<i class="fa-solid fa-spinner fa-spin"></i> ${text}`}else{button.disabled=false;if(button.dataset.original)button.innerHTML=button.dataset.original}}
function updateRefreshTimestamp(){state.lastRefreshAt=new Date();const label=state.lastRefreshAt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});const monitoring=$('#monitoring-updated-at');if(monitoring)monitoring.innerHTML=`<i></i> Dados consultados às ${label}`;const button=$('#refresh-button');if(button)button.title=`Atualizar · última consulta às ${label}`}
function syncMonitoringPolling(){if(state.monitoringTimer){clearInterval(state.monitoringTimer);state.monitoringTimer=null}if(state.currentView==='monitoring'&&!document.hidden){state.monitoringTimer=setInterval(()=>state.realtimeMonitoringAllowed?Promise.all([loadJobs({silent:true}),loadSecurityMonitoring({silent:true})]):loadJobs({silent:true}),5000)}}

async function initialize(){
  if(!token()){location.href='/index.html';return}
  try{
    bindEvents();
    await loadCore();
    renderShell();
    if(!state.bootstrap.onboarding.completed && !sessionStorage.getItem('onboarding_skipped')) openOnboarding();
    $('#app-loading')?.classList.add('hidden');
    Promise.allSettled([loadTrend(),loadJobs(),loadReports(),loadIntegrations()]);
  }catch(error){toast(error.message,'error')}
  finally{$('#app-loading')?.classList.add('hidden')}
}

async function loadCore(){
  const [bootstrap,overview,assets,findings,tasks]=await Promise.all([api('/platform/bootstrap'),api('/security/overview'),api('/assets'),api('/findings?status='),api('/remediation-tasks')]);
  state.bootstrap=bootstrap;state.overview=overview;state.assets=assets;state.findings=findings.findings||[];state.tasks=tasks.tasks||[];
}

function renderShell(){
  const {user,organization}=state.bootstrap;
  const plan=String(user.subscription_plan||'starter').trim().toLowerCase();const subscriptionStatus=String(user.subscription_status||'pending').trim().toLowerCase();const enterpriseActive=plan==='enterprise'&&subscriptionStatus==='active';
  state.realtimeMonitoringAllowed=['professional','enterprise'].includes(plan)&&subscriptionStatus==='active';
  ['#configure-sensor-button','#configure-waf-button'].forEach(selector=>{const button=$(selector);if(button){button.disabled=!state.realtimeMonitoringAllowed;button.title=state.realtimeMonitoringAllowed?'':'Disponível a partir do plano Professional'}});
  const advancedLink=$('#advanced-tools-link');if(advancedLink) advancedLink.hidden=!user.advanced_tools_access;
  const viggioLink=$('#viggio-link');if(viggioLink) viggioLink.hidden=!enterpriseActive;
  $('#sidebar-org').textContent=organization.name;$('#sidebar-plan').textContent=organization.plan;$('#org-avatar').textContent=initials(organization.name);$('#sidebar-user').textContent=user.username;$('#sidebar-role').textContent=organization.role;$('#user-avatar').textContent=initials(user.username);$('#welcome-title').textContent=`Olá, ${user.username}. Aqui está sua segurança.`;$('#settings-org-name').value=organization.name;$('#settings-plan').value=organization.plan;$('#settings-role').value=organization.role;
  renderOverview();renderAssets();renderRisks();renderTimeline(state.bootstrap.activity||[]);
}
function initials(value){return String(value||'IN').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}

function navigate(view){
  if(!labels[view])return;state.currentView=view;
  $$('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));$$('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('#current-view-label').textContent=labels[view];history.replaceState(null,'',`#${view}`);closeMobile();
  const pending=[];if(view==='assets')renderAssets();if(view==='risks')renderRisks();if(view==='monitoring')pending.push(loadJobs(),loadSecurityMonitoring());if(view==='reports')pending.push(loadReports());if(view==='compliance')pending.push(loadCompliance());if(view==='integrations')pending.push(loadIntegrations());if(view==='ai'){ensureAiGreeting('page');pending.push(loadAiActions())}if(view==='settings')pending.push(loadRuntimeSettings());if(pending.length){window.showPageProgress?.();Promise.allSettled(pending).finally(()=>window.hidePageProgress?.())}syncMonitoringPolling();
}

function renderOverview(){
  const o=state.overview||{};const findings=o.findings||{};const assets=o.assets||{};const score=o.security_score??0;
  $('#security-score').textContent=score;$('#score-ring').style.setProperty('--score',score);const status=$('#score-status');status.className='status-pill '+(score<40?'danger':score<70?'warning':'');status.textContent=score>=80?'Boa postura':score>=60?'Atenção':score>=40?'Risco elevado':'Risco crítico';
  $('#score-explanation').textContent=score>=80?'Sua postura está consistente. Continue monitorando mudanças.':score>=60?'Existem riscos relevantes que devem entrar no próximo ciclo de correção.':'Sua organização possui riscos que exigem priorização imediata.';
  $('#metric-critical').textContent=findings.critical||0;$('#metric-high').textContent=findings.high||0;$('#metric-exposed').textContent=assets.internet_exposed||0;$('#metric-remediation').textContent=(state.bootstrap.remediation||{}).open||0;$('#nav-assets-count').textContent=assets.total||0;$('#nav-risks-count').textContent=(findings.critical||0)+(findings.high||0);
  const top=o.top_risks||[];$('#overview-risks').innerHTML=top.length?top.map((risk,index)=>riskRow(risk,index)).join(''):`<div class="empty-state compact"><i class="fa-solid fa-shield-check"></i><p>Nenhum risco aberto.</p></div>`;
  $('#ai-insight-title').textContent=top.length?`Existem ${top.length} riscos que merecem sua atenção.`:'Nenhum risco prioritário foi identificado.';$('#ai-insight-text').textContent=top.length?`O maior risco é “${top[0].title}”, com score ${top[0].risk_score}. Posso explicar o impacto ou criar um plano.`:'Adicione ativos e execute análises para que eu possa orientar sua empresa.';
  const actions=top.slice(0,3);$('#recommended-actions').innerHTML=actions.length?actions.map((risk,index)=>`<div class="action-item"><span>${index+1}</span><div><strong>${escapeHtml(risk.remediation||`Investigar ${risk.title}`)}</strong><small>${escapeHtml(risk.title)} · score ${risk.risk_score}</small></div></div>`).join(''):`<div class="empty-state compact"><p>Nenhuma ação pendente.</p></div>`;
}
function riskRow(risk,index){return `<div class="risk-row" data-risk-id="${risk.id}"><span class="risk-number">${String(index+1).padStart(2,'0')}</span><div><strong>${escapeHtml(risk.title)}</strong><small><span class="severity ${escapeHtml(risk.severity)}">${severityLabel(risk.severity)}</span> · ${escapeHtml(risk.scanner_source||'Iron AI')}</small></div><span class="risk-score">${risk.risk_score||0}</span></div>`}

async function loadTrend(){const data=await api(`/security/trend?days=${$('#trend-period').value}`);renderTrend(data.snapshots||[])}
function renderTrend(items){const chart=$('#trend-chart');if(!items.length){chart.innerHTML='<div class="empty-chart">Crie snapshots para acompanhar sua evolução.</div>';return}chart.innerHTML=items.slice(-30).map(item=>`<div class="trend-bar-wrap" data-value="${item.score}"><div class="trend-bar" style="height:${Math.max(item.score,3)}%"></div></div>`).join('')}
function renderTimeline(items){const box=$('#security-timeline');box.innerHTML=items.length?items.slice(0,7).map(item=>`<div class="timeline-item"><strong>${escapeHtml(actionLabels[item.action]||item.action.replaceAll('_',' '))}</strong><small>${dateLabel(item.created_at)}</small></div>`).join(''):`<div class="empty-state compact"><p>A atividade da organização aparecerá aqui.</p></div>`}

function renderAssets(){
  const search=($('#asset-search')?.value||'').toLowerCase();const env=$('#asset-environment-filter')?.value||'';const filtered=state.assets.filter(asset=>(!search||asset.name.toLowerCase().includes(search))&&(!env||asset.environment===env));
  $('#assets-total').textContent=state.assets.length;$('#assets-production').textContent=state.assets.filter(a=>a.environment==='production').length;$('#assets-exposed').textContent=state.assets.filter(a=>a.internet_exposed).length;$('#assets-critical').textContent=state.assets.filter(a=>a.criticality==='critical').length;
  $('#assets-table').innerHTML=filtered.length?filtered.map(asset=>`<tr><td><div class="asset-cell"><span class="asset-icon"><i class="fa-solid ${assetIcon(asset.type)}"></i></span><div><strong>${escapeHtml(asset.name)}</strong><small>${escapeHtml(asset.hostname||asset.url||asset.ip_address||'Ativo monitorado')}</small></div></div></td><td>${escapeHtml(asset.type.replaceAll('_',' '))}</td><td>${escapeHtml(asset.environment)}</td><td><span class="exposure-badge ${asset.internet_exposed?'':'internal'}"><i class="fa-solid ${asset.internet_exposed?'fa-globe':'fa-lock'}"></i>${asset.internet_exposed?'Internet':'Interno'}</span></td><td><span class="severity ${asset.criticality}">${severityLabel(asset.criticality)}</span></td><td>${asset.metadata?.last_scan?dateLabel(asset.metadata.last_scan):dateLabel(asset.last_seen_at)}</td><td>${isWebAsset(asset)?`<button class="row-action scan-row-action" data-scan-asset="${asset.id}" title="Executar scan real"><i class="fa-solid fa-magnifying-glass-chart"></i></button>`:''}</td></tr>`).join(''):`<tr><td colspan="7"><div class="empty-state compact"><p>Nenhum ativo encontrado.</p></div></td></tr>`;
}
function assetIcon(type){return ({domain:'fa-globe',subdomain:'fa-sitemap',ip_address:'fa-network-wired',server:'fa-server',web_application:'fa-window-maximize',api:'fa-code-branch',repository:'fa-code',container:'fa-cube',cloud_resource:'fa-cloud'}[type]||'fa-server')}
function isWebAsset(asset){return ['domain','subdomain','web_application','api'].includes(asset.type)}
function openScanModal(assetId){const assets=state.assets.filter(isWebAsset);if(!assets.length){toast('Adicione primeiro um domínio, aplicação web ou API.','error');openModal('#asset-modal');return}$('#scan-asset-select').innerHTML=assets.map(asset=>`<option value="${asset.id}" ${Number(assetId)===asset.id?'selected':''}>${escapeHtml(asset.name)}</option>`).join('');openModal('#scan-modal')}
async function startWebScan(event){event.preventDefault();const button=event.submitter;const assetId=Number($('#scan-asset-select').value);const authenticated=$('#scan-authenticated').checked;setBusy(button,true,'Enfileirando...');try{if(authenticated&&$('#scan-auth-secret').value){await api('/scan-profiles',{method:'POST',body:JSON.stringify({asset_id:assetId,auth_type:$('#scan-auth-type').value,header_name:$('#scan-auth-type').value==='api_key'?$('#scan-auth-header').value:null,secret:$('#scan-auth-secret').value})});$('#scan-auth-secret').value=''}const job=await api('/scan-jobs',{method:'POST',body:JSON.stringify({job_type:authenticated?'authenticated_web_scan':'web_security_scan',asset_id:assetId})});closeModals();navigate('monitoring');toast(`${authenticated?'DAST autenticado':'Scan real'} #${job.id} iniciado.`);await loadJobs();pollJob(job.id)}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
function pollJob(jobId){let attempts=0;const timer=setInterval(async()=>{attempts++;await loadJobs();const job=state.jobs.find(item=>item.id===jobId);if(!job||['completed','failed'].includes(job.status)||attempts>45){clearInterval(timer);await refreshCore();if(job?.status==='completed')toast(`Scan concluído: ${job.result?.findings_total||0} findings reais.`);if(job?.status==='failed')toast(job.error||'O scan falhou.','error')}},2000)}

function renderRisks(){
  const selected=$('.filter-chip.active')?.dataset.severity||'';const status=$('#risk-status-filter')?.value??'open';const filtered=state.findings.filter(item=>(!selected||item.severity===selected)&&(!status||item.status===status));$('#risk-total-chip').textContent=state.findings.length;
  $('#risks-table').innerHTML=filtered.length?filtered.map(risk=>`<tr data-risk-id="${risk.id}"><td><strong>${escapeHtml(risk.title)}</strong><small>${escapeHtml(risk.scanner_source||'Iron AI finding')}</small></td><td><span class="severity ${risk.severity}">${severityLabel(risk.severity)}</span></td><td><strong>${risk.risk_score||0}</strong></td><td>#${risk.asset_id||'—'}</td><td>${statusLabel(risk.status)}</td><td>${dateLabel(risk.last_seen_at)}</td><td><button class="row-action" aria-label="Abrir risco"><i class="fa-solid fa-chevron-right"></i></button></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty-state compact"><p>Nenhum risco neste filtro.</p></div></td></tr>`;
}

async function openRisk(id){
  try{const risk=await api(`/findings/${id}`);state.currentFinding=risk;$('#ai-context').innerHTML=`<i class="fa-solid fa-triangle-exclamation"></i><span>Contexto: ${escapeHtml(risk.title)}</span>`;$('#risk-detail').innerHTML=`<span class="severity ${risk.severity}">${severityLabel(risk.severity)}</span><h1>${escapeHtml(risk.title)}</h1><div class="risk-meta"><span class="status-pill">Score ${risk.risk_score}</span><span class="status-pill">${escapeHtml(risk.confidence)}</span><span class="status-pill">${statusLabel(risk.status)}</span></div><div class="detail-section"><h3>Resumo executivo</h3><p>${escapeHtml(risk.description||'Sem descrição adicional.')}</p></div><div class="detail-section"><h3>Por que este score?</h3><div class="risk-factor-grid">${Object.entries(risk.risk_factors||{}).map(([name,value])=>`<div class="risk-factor"><span>${escapeHtml(name.replaceAll('_',' '))}</span><strong>+${value}</strong></div>`).join('')}</div></div><div class="detail-section"><h3>Evidência</h3><pre>${escapeHtml(risk.evidence||'Nenhuma evidência armazenada.')}</pre></div><div class="detail-section"><h3>Como corrigir</h3><p>${escapeHtml(risk.remediation||'Ainda não há orientação registrada.')}</p></div><div class="detail-section"><h3>Atualizar status</h3><div class="risk-status-actions"><button data-set-risk-status="in_progress">Iniciar correção</button><button data-set-risk-status="resolved">Marcar resolvido</button><button data-set-risk-status="accepted_risk">Aceitar risco</button><button data-set-risk-status="false_positive">Falso positivo</button></div></div><div class="risk-ai-actions"><button class="secondary-button full" data-propose-current-risk><i class="fa-solid fa-list-check"></i> Propor tarefa de correção</button><button class="primary-button full" data-ask-current-risk><i class="fa-solid fa-wand-magic-sparkles"></i> Perguntar à Iron AI</button></div>`;if(state.integrations.some(item=>item.provider==='jira'&&item.status==='connected'))$('#risk-detail').insertAdjacentHTML('beforeend','<button class="secondary-button full" data-create-jira-issue><i class="fa-brands fa-jira"></i> Criar tarefa no Jira</button>');$('#risk-drawer').classList.add('open')}
  catch(error){toast(error.message,'error')}
}
async function setRiskStatus(status){if(!state.currentFinding)return;const confirmations={resolved:{variant:'info',icon:'fa-circle-check',title:'Marcar risco como resolvido?',message:'Confirme que a correção foi aplicada e validada.',confirmText:'Marcar resolvido',confirmIcon:'fa-check'},accepted_risk:{variant:'warning',icon:'fa-triangle-exclamation',title:'Aceitar este risco?',message:'O risco continuará existindo, mas deixará a fila de correção ativa.',details:'Registre esta decisão somente após avaliar impacto e responsabilidade.',confirmText:'Aceitar risco',confirmIcon:'fa-check'},false_positive:{variant:'warning',icon:'fa-filter-circle-xmark',title:'Marcar como falso positivo?',message:'O finding deixará a fila de riscos ativos.',details:'Confirme que a evidência foi revisada.',confirmText:'Marcar falso positivo',confirmIcon:'fa-check'}};if(confirmations[status]&&!await showConfirmDialog(confirmations[status]))return;window.showPageProgress?.();try{await api(`/findings/${state.currentFinding.id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast(`Risco atualizado: ${statusLabel(status)}`);$('#risk-drawer').classList.remove('open');await refreshCore()}catch(error){toast(error.message,'error')}finally{window.hidePageProgress?.()}}

async function loadJobs(options={}){try{const data=await api('/scan-jobs');state.jobs=data.jobs||[];$('#jobs-queued').textContent=state.jobs.filter(x=>x.status==='queued').length;$('#jobs-running').textContent=state.jobs.filter(x=>x.status==='running').length;$('#jobs-completed').textContent=state.jobs.filter(x=>x.status==='completed').length;$('#jobs-list').innerHTML=state.jobs.length?state.jobs.map(job=>{const result=job.result||{};const detail=['web_security_scan','authenticated_web_scan'].includes(job.job_type)&&job.status==='completed'?`HTTP ${result.http_status} · ${result.response_time_ms} ms · ${result.findings_total} findings · ${escapeHtml((result.ip_addresses||[]).join(', '))}`:`progresso ${job.progress}%`;return `<div class="job-row"><span class="job-icon"><i class="fa-solid ${job.status==='completed'?'fa-check':job.status==='failed'?'fa-triangle-exclamation':'fa-gears'}"></i></span><div><strong>${['web_security_scan','authenticated_web_scan'].includes(job.job_type)?job.job_type==='authenticated_web_scan'?'DAST autenticado real':'Scan web real':escapeHtml(job.job_type.replaceAll('_',' '))}</strong><small>${dateLabel(job.created_at)} · ${detail}${job.error?` · ${escapeHtml(job.error)}`:''}</small></div><span class="job-status ${job.status}">${statusLabel(job.status)}</span></div>`}).join(''):`<div class="empty-state compact"><p>Nenhum job processado.</p></div>`;updateRefreshTimestamp();return true}catch(error){if(!options.silent)toast(error.message,'error');return false}}
async function loadSecurityMonitoring(options={}){if(!state.realtimeMonitoringAllowed){const box=$('#monitoring-coverage');box.className='monitoring-coverage panel partial';box.innerHTML='<i class="fa-solid fa-lock"></i><div><strong>Monitoramento em tempo real disponível no Professional</strong><span>Faça upgrade para conectar sensores, receber alertas contínuos e executar contenção aprovada no Cloudflare WAF.</span></div><a class="secondary-button" href="/pricing.html">Ver planos</a>';$('#security-events-list').innerHTML='<div class="empty-state compact"><p>Os scans sob demanda continuam disponíveis no Starter.</p></div>';return false}try{const data=await api('/security-monitoring/overview');const previous=state.latestSecurityEventId;state.securityMonitoring=data;state.securityEvents=data.events||[];state.latestSecurityEventId=data.latest_id||previous;$('#security-events-critical').textContent=data.metrics.critical;$('#security-events-open').textContent=data.metrics.open;$('#security-sensors-active').textContent=data.metrics.active_sensors;$('#security-active-blocks').textContent=data.metrics.active_blocks;renderSecurityCoverage(data);renderSecurityEvents(data);if(previous&&data.events.some(event=>event.id>previous)){const newest=data.events.find(event=>event.id>previous);toast(`${newest.severity==='critical'?'Incidente crítico':'Nova detecção'}: ${newest.title}`,newest.severity==='critical'?'error':'success')}updateRefreshTimestamp();return true}catch(error){if(!options.silent)toast(error.message,'error');return false}}
function renderSecurityCoverage(data){const box=$('#monitoring-coverage');const sensors=data.metrics.active_sensors||0;if(sensors&&data.cloudflare_connected){box.className='monitoring-coverage panel live';box.innerHTML=`<i class="fa-solid fa-shield-check"></i><div><strong>Detecção e contenção conectadas</strong><span>${sensors} sensor(es) enviando telemetria · Cloudflare WAF pronto para bloqueio aprovado.</span></div>`}else if(sensors){box.className='monitoring-coverage panel partial';box.innerHTML=`<i class="fa-solid fa-satellite-dish"></i><div><strong>Detecção ativa; contenção ainda manual</strong><span>A telemetria está chegando, mas conecte o Cloudflare WAF para bloquear uma origem pela plataforma.</span></div>`}else{box.className='monitoring-coverage panel';box.innerHTML=`<i class="fa-solid fa-triangle-exclamation"></i><div><strong>Sem telemetria em tempo real</strong><span>Scans externos continuam disponíveis, mas ataques ao ativo só serão detectados após conectar um sensor, proxy ou WAF.</span></div>`}}
function renderSecurityEvents(data){const canManage=['owner','admin'].includes(state.bootstrap?.organization?.role);$('#security-events-list').innerHTML=state.securityEvents.length?state.securityEvents.map(event=>{const blockControl=event.containment_status==='blocked'?`<span class="contained-badge"><i class="fa-solid fa-ban"></i> Origem bloqueada</span>${event.containment_action_id&&canManage?`<button class="text-button" data-release-containment="${event.containment_action_id}">Remover bloqueio</button>`:''}`:event.source_ip&&canManage?(data.cloudflare_connected?`<button class="danger-button" data-contain-event="${event.id}"><i class="fa-solid fa-ban"></i> Bloquear ${escapeHtml(event.source_ip)}</button>`:'<button class="secondary-button" data-open-waf><i class="fa-solid fa-link"></i> Conectar WAF para bloquear</button>'):'';const statusControl=event.status==='resolved'?'<span class="contained-badge">Resolvido</span>':`<button class="text-button" data-resolve-security-event="${event.id}">Marcar resolvido</button>`;return `<article class="security-event ${escapeHtml(event.severity)}"><span class="security-event-icon"><i class="fa-solid ${event.event_type==='ddos'?'fa-gauge-high':event.event_type.includes('scan')?'fa-magnifying-glass':'fa-shield-virus'}"></i></span><div class="security-event-main"><h3>${escapeHtml(event.title)}</h3><p>${escapeHtml(event.description)}</p><div class="security-event-meta"><span>${escapeHtml(event.asset_name||`Ativo #${event.asset_id}`)}</span><span>${severityLabel(event.severity)}</span><span>${dateLabel(event.last_seen_at)}</span><span>${event.request_count} requisições</span>${event.status_code?`<span>HTTP ${event.status_code}</span>`:''}</div><div class="security-remediation"><strong>Como conter e resolver</strong>${escapeHtml(event.remediation)}</div></div><div class="security-event-actions">${blockControl}${statusControl}<button class="text-button" data-security-ai="${event.id}">Perguntar à Iron AI</button></div></article>`}).join(''):`<div class="empty-state compact"><i class="fa-solid fa-shield-halved"></i><p>Nenhuma tentativa hostil foi detectada pela telemetria conectada.</p></div>`}
async function containSecurityEvent(id,button){const incident=state.securityEvents.find(item=>String(item.id)===String(id));if(!await showConfirmDialog({variant:'warning',icon:'fa-shield-halved',title:'Bloquear origem no Cloudflare WAF',message:`A origem ${incident?.source_ip||'informada'} será bloqueada nesta zona e a regra afetará tráfego real.`,details:'Confirme se o IP e a zona correspondem ao incidente investigado.',confirmText:'Bloquear origem',confirmIcon:'fa-ban'}))return;setBusy(button,true,'Bloqueando...');try{await api(`/security-monitoring/events/${id}/contain`,{method:'POST'});toast('Origem bloqueada no Cloudflare WAF.');await loadSecurityMonitoring()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function releaseContainment(id,button){if(!await showConfirmDialog({variant:'warning',icon:'fa-shield',title:'Remover bloqueio do WAF',message:'A origem poderá voltar a acessar os ativos protegidos por esta regra.',details:'Remova o bloqueio somente após confirmar que a ameaça foi tratada.',confirmText:'Remover bloqueio',confirmIcon:'fa-unlock'}))return;setBusy(button,true,'Removendo...');try{await api(`/security-monitoring/containment/${id}`,{method:'DELETE'});toast('Bloqueio removido do Cloudflare WAF.');await loadSecurityMonitoring()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function resolveSecurityEvent(id,button){if(!await showConfirmDialog({variant:'info',icon:'fa-circle-check',title:'Marcar incidente como resolvido?',message:'Confirme que a ameaça foi contida e que as verificações necessárias foram concluídas.',confirmText:'Marcar resolvido',confirmIcon:'fa-check'}))return;setBusy(button,true,'Salvando...');try{await api(`/security-monitoring/events/${id}`,{method:'PATCH',body:JSON.stringify({status:'resolved'})});toast('Incidente marcado como resolvido.');await loadSecurityMonitoring()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function loadSecuritySensors(){try{const data=await api('/security-monitoring/sensors');$('#security-sensors-list').innerHTML=(data.sensors||[]).length?data.sensors.map(sensor=>`<div class="security-sensor-row"><div><strong>${escapeHtml(sensor.name)}</strong><small>${escapeHtml(sensor.key_prefix)}… · ${sensor.revoked_at?'revogado':sensor.last_seen_at?`último evento ${dateLabel(sensor.last_seen_at)}`:'aguardando primeiro evento'}</small></div>${sensor.revoked_at?'':`<button class="row-action" data-revoke-security-sensor="${sensor.id}" title="Revogar sensor"><i class="fa-solid fa-ban"></i></button>`}</div>`).join(''):'<p class="modal-copy">Nenhum sensor criado.</p>'}catch(error){toast(error.message,'error')}}
function openSensorConfiguration(){const assets=state.assets.filter(asset=>asset.status!=='inactive');if(!assets.length){toast('Adicione um ativo antes de criar o sensor.','error');navigate('assets');return}$('#sensor-asset').innerHTML=assets.map(asset=>`<option value="${asset.id}">${escapeHtml(asset.name)}</option>`).join('');$('#sensor-key-reveal').hidden=true;openModal('#sensor-modal');loadSecuritySensors()}
async function createSecuritySensor(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Criando...');try{const result=await api('/security-monitoring/sensors',{method:'POST',body:JSON.stringify({asset_id:Number($('#sensor-asset').value),name:$('#sensor-name').value.trim(),expires_in_days:365})});$('#sensor-secret').textContent=result.key;$('#sensor-key-reveal').hidden=false;$('#sensor-name').value='';toast('Sensor criado. Copie a chave agora.');await loadSecuritySensors()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function revokeSecuritySensor(id,button){if(!await showConfirmDialog({title:'Revogar sensor',message:'Este sensor deixará de enviar telemetria para a organização.',details:'A chave atual será invalidada e não poderá ser recuperada.',confirmText:'Revogar sensor',confirmIcon:'fa-satellite-dish'}))return;setBusy(button,true,'');try{await api(`/security-monitoring/sensors/${id}`,{method:'DELETE'});toast('Sensor revogado.');await Promise.all([loadSecuritySensors(),loadSecurityMonitoring()])}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function connectCloudflareWaf(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Validando...');try{const result=await api('/security-monitoring/cloudflare/connect',{method:'POST',body:JSON.stringify({zone_id:$('#cloudflare-zone-id').value.trim(),api_token:$('#cloudflare-api-token').value})});$('#cloudflare-api-token').value='';closeModals();toast(`Cloudflare WAF conectado${result.zone_name?` · ${result.zone_name}`:''}.`);await loadSecurityMonitoring()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function refreshJobs(button){setBusy(button,true,'Atualizando...');try{const ok=await loadJobs();if(!ok)throw new Error('Não foi possível consultar os jobs.');toast('Monitoramento atualizado com dados do servidor.')}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function createSnapshot(){const button=$('#snapshot-button');setBusy(button,true,'Criando...');try{await api('/security/snapshot',{method:'POST'});toast('Snapshot de segurança criado.');await Promise.all([loadTrend(),refreshCore()])}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}

async function loadReports(){try{const data=await api('/reports');state.reports=data.reports||[];$('#reports-list').innerHTML=state.reports.length?state.reports.map(report=>`<div class="report-row"><span class="report-icon"><i class="fa-regular fa-file-pdf"></i></span><div><strong>Relatório ${report.report_type==='executive'?'Executivo':'Técnico'}</strong><small>${report.period_days} dias · ${dateLabel(report.created_at)}</small></div><a href="#" data-download-report="${report.id}">Baixar PDF <i class="fa-solid fa-download"></i></a></div>`).join(''):`<div class="empty-state compact"><p>Nenhum relatório gerado.</p></div>`;return true}catch(error){toast(error.message,'error');return false}}
async function generateReport(type,button){setBusy(button,true,'Gerando...');try{await api(`/reports/${type}?period_days=30`,{method:'POST'});toast('Relatório gerado com métricas atuais.');await loadReports()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function downloadReport(id){try{const response=await fetch(`${API}/reports/${id}/pdf`,{headers:{Authorization:`Bearer ${token()}`}});if(!response.ok)throw new Error('Não foi possível gerar o PDF.');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`iron-ai-report-${id}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){toast(error.message,'error')}}

async function loadCompliance(){
  try{state.compliance=await api('/compliance');renderCompliance();return true}catch(error){toast(error.message,'error');$('#compliance-controls').innerHTML=`<div class="empty-state compact"><p>${escapeHtml(error.message)}</p></div>`;return false}
}
function renderCompliance(){
  const data=state.compliance;if(!data)return;const canManage=['owner','admin'].includes(state.bootstrap?.organization?.role);$('#compliance-score').textContent=data.score;$('.compliance-score').style.setProperty('--compliance-progress',`${data.score}%`);$('#compliance-summary').textContent=`${data.implemented} de ${data.total} controles implementados`;$('#compliance-disclaimer').textContent=data.disclaimer;
  $('#compliance-controls').innerHTML=data.controls.map(control=>`<article class="compliance-control panel" data-compliance-control="${escapeHtml(control.key)}"><div class="compliance-control-head"><div><h3>${escapeHtml(control.title)}</h3><p>${escapeHtml(control.description)}</p></div><span class="compliance-status ${escapeHtml(control.status)}">${statusLabel(control.status)}</span></div><span class="compliance-framework">${escapeHtml(control.framework)}${control.automated?' · automático':''}</span><div class="compliance-evidence"><i class="fa-solid fa-paperclip"></i> ${escapeHtml(control.evidence||'Nenhuma evidência registrada.')}</div>${!control.automated&&canManage?`<div class="compliance-controls"><textarea maxlength="4000" aria-label="Evidência de ${escapeHtml(control.title)}" placeholder="Informe o documento, data, responsável ou evidência verificável...">${escapeHtml(control.evidence||'')}</textarea><select aria-label="Status"><option value="not_started" ${control.status==='not_started'?'selected':''}>Não iniciado</option><option value="in_progress" ${control.status==='in_progress'?'selected':''}>Em andamento</option><option value="implemented" ${control.status==='implemented'?'selected':''}>Implementado</option></select><button class="secondary-button" data-save-compliance="${escapeHtml(control.key)}">Salvar</button></div>`:''}</article>`).join('');
}
async function saveCompliance(button){const card=button.closest('[data-compliance-control]');const status=card.querySelector('select').value;const evidence=card.querySelector('textarea').value.trim();if(status==='implemented'&&!evidence){toast('Registre uma evidência antes de marcar como implementado.','error');return}setBusy(button,true,'Salvando...');try{await api(`/compliance/${button.dataset.saveCompliance}`,{method:'PATCH',body:JSON.stringify({status,evidence:evidence||null})});toast('Controle e evidência atualizados.');await Promise.all([loadCompliance(),refreshCore()])}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}

async function loadRuntimeSettings(){
  try{
    const [runtime,plan,mfa]=await Promise.all([api('/platform/runtime-status'),api('/user/subscription-info'),api('/auth/mfa/status')]);
    $('#runtime-security').innerHTML=`<div><span>Iron AI</span><strong>${runtime.ai.connected?`Conectada · ${escapeHtml(runtime.ai.provider)}`:'Fallback local'}</strong></div><div><span>Banco de dados</span><strong>${escapeHtml(runtime.database)}</strong></div><div><span>Isolamento tenant</span><strong>${runtime.tenant_isolation?'Ativo':'Inativo'}</strong></div><div><span>Fila de jobs</span><strong>${escapeHtml(runtime.background_queue)}</strong></div>`;
    const limit=plan.scans_limit<0?'Ilimitado':plan.scans_limit;
    const validity=plan.subscription_end?new Date(plan.subscription_end).toLocaleDateString('pt-BR'):'renovação mensal';
    $('#runtime-plan').innerHTML=`<div><span>Plano</span><strong>${escapeHtml(plan.subscription_plan)}</strong></div><div><span>Status</span><strong>${escapeHtml(plan.subscription_status)}</strong></div><div><span>Scans no mês</span><strong>${plan.scans_this_month} / ${limit}</strong></div><div><span>Válido até</span><strong>${validity}</strong></div>`;
    const cancelButton=$('#cancel-subscription-button');
    const canCancel=Boolean(plan.can_cancel_recurring);
    cancelButton.hidden=!canCancel;
    if(!canCancel)closeCancelSubscription();
    const refundEligible=Boolean(plan.is_trial&&plan.trial_ends_at&&new Date(plan.trial_ends_at)>=new Date());
    const endLabel=plan.trial_ends_at?new Date(plan.trial_ends_at).toLocaleDateString('pt-BR'):'';
    $('#cancel-subscription-copy').textContent=refundEligible?`Você está na janela de ${plan.cancellation_window_days||7} dias. O pagamento inicial será solicitado para estorno ao provedor. Elegível até ${endLabel}.`:'A assinatura Starter recorrente será encerrada após a confirmação do Stripe. Fora da janela de 7 dias não há estorno automático.';
    let card=$('#mfa-card');
    if(!card){$('#runtime-security').insertAdjacentHTML('afterend','<div class="mfa-card" id="mfa-card"><div><strong>Autenticação em duas etapas</strong><small id="mfa-status"></small></div><button class="secondary-button" type="button" id="mfa-setup-button">Configurar MFA</button></div><div id="mfa-setup-box" class="mfa-setup-box" hidden><strong>Adicione a conta “Iron AI” no seu autenticador</strong><small>Digite esta chave manualmente no seu aplicativo autenticador.</small><code id="mfa-secret"></code><label>Código de 6 dígitos<input id="mfa-confirm-code" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></label><button class="primary-button" type="button" id="mfa-confirm-button">Confirmar e ativar</button></div><div id="mfa-recovery-box" class="mfa-setup-box" hidden><strong>Códigos de recuperação — salve agora</strong><code id="mfa-recovery-codes"></code></div>');card=$('#mfa-card')}
    $('#mfa-status').textContent=mfa.enabled?'Ativado — sua conta exige código no login.':'Desativado — ative para proteger sua conta.';
    $('#mfa-setup-button').textContent=mfa.enabled?'Desativar MFA':'Configurar MFA';
    $('#mfa-setup-button').dataset.enabled=mfa.enabled?'true':'false';
    return await loadAssuranceSettings();
  }catch(error){toast(error.message,'error');return false}
}
function openCancelSubscription(){const box=$('#cancel-subscription-box');box.hidden=false;$('#cancel-subscription-confirmation').focus()}
function closeCancelSubscription(){const box=$('#cancel-subscription-box');const input=$('#cancel-subscription-confirmation');const button=$('#confirm-cancel-subscription');if(box)box.hidden=true;if(input)input.value='';if(button)button.disabled=true}
function validateCancellationConfirmation(){const confirmed=$('#cancel-subscription-confirmation').value.trim().toUpperCase()==='CANCELAR';$('#confirm-cancel-subscription').disabled=!confirmed}
async function cancelActiveSubscription(){const input=$('#cancel-subscription-confirmation');if(input.value.trim().toUpperCase()!=='CANCELAR'){toast('Digite CANCELAR para confirmar.','error');return}const button=$('#confirm-cancel-subscription');setBusy(button,true,'Cancelando...');try{const result=await api('/payments/cancel-subscription',{method:'POST'});toast(result.message||'Assinatura cancelada com sucesso.');closeCancelSubscription();await loadCore();renderShell();await loadRuntimeSettings()}catch(error){toast(error.message,'error')}finally{setBusy(button,false);validateCancellationConfirmation()}}
function selectSettingsTab(tab){$$('[data-settings-tab]').forEach(button=>button.classList.toggle('active',button.dataset.settingsTab===tab));$$('[data-settings-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.settingsPanel===tab));if(tab==='devsecops')loadPipelineKeys();else if(tab!=='organization')loadRuntimeSettings()}

async function loadPipelineKeys(){
  const box=$('#pipeline-keys-list');if(!box)return;
  try{const data=await api('/pipeline-keys');const keys=data.keys||[];box.innerHTML=keys.length?keys.map(key=>`<div class="pipeline-key-row"><div><strong>${escapeHtml(key.name)}</strong><small>${escapeHtml(key.key_prefix)}… · ${key.revoked_at?'Revogada':key.last_used_at?`usada ${dateLabel(key.last_used_at)}`:'nunca utilizada'}</small></div>${key.revoked_at?'':`<button class="row-action" data-revoke-pipeline-key="${key.id}" title="Revogar chave"><i class="fa-solid fa-ban"></i></button>`}</div>`).join(''):'<div class="empty-state compact"><p>Nenhuma chave de pipeline criada.</p></div>'}catch(error){box.innerHTML=`<div class="empty-state compact"><p>${escapeHtml(error.message)}</p></div>`}}
async function createPipelineKey(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Criando...');try{const result=await api('/pipeline-keys',{method:'POST',body:JSON.stringify({name:$('#pipeline-key-name').value.trim(),expires_in_days:Number($('#pipeline-key-expiry').value)})});$('#pipeline-key-secret').textContent=result.key;$('#pipeline-key-reveal').hidden=false;event.target.reset();toast('Chave criada. Copie e armazene como secret do pipeline.');await loadPipelineKeys()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function revokePipelineKey(id,button){if(!await showConfirmDialog({title:'Revogar chave de pipeline',message:'Os pipelines que usam esta chave perderão acesso imediatamente.',details:'Atualize o CI/CD com uma nova chave antes de revogar se o pipeline precisar continuar ativo.',confirmText:'Revogar chave',confirmIcon:'fa-key'}))return;setBusy(button,true,'');try{await api(`/pipeline-keys/${id}`,{method:'DELETE'});toast('Chave de pipeline revogada.');await loadPipelineKeys()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function setupOrDisableMfa(){const button=$('#mfa-setup-button');if(button.dataset.enabled==='true'){const code=await showConfirmDialog({variant:'warning',icon:'fa-mobile-screen-button',title:'Desativar MFA',message:'Sua conta perderá a proteção do segundo fator.',details:'Informe o código atual ou um código de recuperação para confirmar.',confirmText:'Desativar MFA',confirmIcon:'fa-unlock',input:{type:'password',placeholder:'Código MFA ou de recuperação',label:'Código MFA',required:true}});if(!code)return;setBusy(button,true,'Desativando...');try{await api('/auth/mfa/disable',{method:'POST',body:JSON.stringify({code})});$('#mfa-setup-box').hidden=true;$('#mfa-recovery-box').hidden=true;toast('MFA desativado.');await loadRuntimeSettings()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}return}setBusy(button,true,'Preparando...');try{const result=await api('/auth/mfa/setup',{method:'POST'});$('#mfa-secret').textContent=result.secret;$('#mfa-setup-box').hidden=false;$('#mfa-recovery-box').hidden=true;$('#mfa-confirm-code').value='';toast('Adicione a chave no autenticador e confirme um código.')}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function confirmMfa(){const button=$('#mfa-confirm-button');const code=$('#mfa-confirm-code').value.trim();if(!code){toast('Digite o código do autenticador.','error');return}setBusy(button,true,'Validando...');try{const result=await api('/auth/mfa/confirm',{method:'POST',body:JSON.stringify({code})});$('#mfa-recovery-codes').textContent=result.recovery_codes.join('\n');$('#mfa-recovery-box').hidden=false;$('#mfa-setup-box').hidden=true;toast('MFA ativado. Salve os códigos de recuperação.');await loadRuntimeSettings()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function loadAssuranceSettings(){let ok=true;try{const sso=await api('/sso/config');$('#sso-issuer').value=sso.issuer||'';$('#sso-client-id').value=sso.client_id||'';$('#sso-domains').value=(sso.allowed_domains||[]).join(', ');$('#sso-require-mfa').checked=sso.require_mfa_claim!==false;$('#sso-login-hint').textContent=`Identificador para o login: ${sso.organization_slug}${sso.enabled?' · SSO ativo':''}`}catch(error){ok=false;$('#sso-login-hint').textContent=error.message}try{const status=await api('/operations/status');$('#operations-status').innerHTML=`<div><span>Estado</span><strong>${status.status==='healthy'?'Saudável':'Degradado'}</strong></div><div><span>Worker</span><strong>${status.processes.worker.healthy?`${status.processes.worker.instances} ativo(s)`:'Sem heartbeat'}</strong></div><div><span>Scheduler</span><strong>${status.processes.scheduler.healthy?`${status.processes.scheduler.instances} ativo(s)`:'Sem heartbeat'}</strong></div><div><span>Jobs na fila</span><strong>${status.queued_jobs}</strong></div>`}catch(error){ok=false;$('#operations-status').innerHTML=`<p>${escapeHtml(error.message)}</p>`}return ok}
async function saveSSOConfig(event){event.preventDefault();const button=event.submitter;const secret=$('#sso-client-secret').value;if(!secret){toast('Informe o client secret para validar e salvar.','error');return}setBusy(button,true,'Validando...');try{await api('/sso/config',{method:'PUT',body:JSON.stringify({issuer:$('#sso-issuer').value,client_id:$('#sso-client-id').value,client_secret:secret,allowed_domains:$('#sso-domains').value.split(',').map(x=>x.trim()).filter(Boolean),require_mfa_claim:$('#sso-require-mfa').checked,enabled:true})});$('#sso-client-secret').value='';toast('SSO Enterprise validado e ativado.');await loadAssuranceSettings()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function downloadAuditExport(){const button=$('#download-audit-export');setBusy(button,true,'Gerando...');try{const response=await fetch(`${API}/audit/export`,{method:'POST',headers:{Authorization:`Bearer ${token()}`}});if(!response.ok){const data=await response.json();throw new Error(data.detail||'Falha ao gerar pacote')}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='iron-ai-audit-evidence.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`Pacote gerado · SHA-256 ${response.headers.get('X-Iron-AI-SHA256')?.slice(0,12)||'registrado'}…`)}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}

async function loadIntegrations(){try{const data=await api('/integrations');state.integrations=data.integrations||[];['github','gitlab','azure_devops','jira'].forEach(provider=>{const connected=state.integrations.find(item=>item.provider===provider&&item.status==='connected');const status=$(`#${provider}-status`);const button=$(`[data-integration-action="${provider}"]`);if(status){const synced=connected?.last_synced_at?` · sincronizado ${dateLabel(connected.last_synced_at)}`:'';status.textContent=connected?`Conectado${connected.configuration?.account?` · ${connected.configuration.account}`:''}${synced}`:'Não conectado';status.classList.toggle('connected',!!connected)}if(button){button.textContent=connected?'Sincronizar agora':'Conectar';button.dataset.integrationId=connected?.id||''}});return true}catch(error){toast(error.message,'error');return false}}
async function connectGithub(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Validando...');try{await api('/integrations/github/connect',{method:'POST',body:JSON.stringify({token:$('#github-token').value})});closeModals();$('#github-token').value='';toast('GitHub conectado com segurança.');await loadIntegrations()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function connectGitLab(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Validando...');try{await api('/integrations/gitlab/connect',{method:'POST',body:JSON.stringify({token:$('#gitlab-token').value,base_url:$('#gitlab-url').value})});closeModals();$('#gitlab-token').value='';toast('GitLab conectado com segurança.');await loadIntegrations()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function connectAzureDevOps(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Validando...');try{await api('/integrations/azure-devops/connect',{method:'POST',body:JSON.stringify({token:$('#azure-devops-token').value,organization:$('#azure-devops-organization').value})});closeModals();$('#azure-devops-token').value='';toast('Azure DevOps conectado com segurança.');await loadIntegrations()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function connectJira(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Validando...');try{await api('/integrations/jira/connect',{method:'POST',body:JSON.stringify({token:$('#jira-token').value,base_url:$('#jira-url').value,email:$('#jira-email').value,project_key:$('#jira-project').value||null})});closeModals();$('#jira-token').value='';toast('Jira conectado com segurança.');await loadIntegrations()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function integrationAction(provider,button){const id=button.dataset.integrationId;if(!id){openModal(`#${provider}-modal`);return}setBusy(button,true,'Sincronizando...');try{const result=await api(`/integrations/${id}/sync`,{method:'POST'});toast(provider==='jira'?`${result.projects} projetos sincronizados.`:`${result.repositories} repositórios sincronizados.`);await refreshCore()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function createJiraIssue(){if(!state.currentFinding)return;const button=$('[data-create-jira-issue]');setBusy(button,true,'Criando...');try{const result=await api('/integrations/jira/issues',{method:'POST',body:JSON.stringify({finding_id:state.currentFinding.id})});toast(`Tarefa ${result.key} criada no Jira.`);if(result.url)window.open(result.url,'_blank','noopener')}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}

function openAi(prompt){$('#ai-drawer').classList.add('open');$('#ai-drawer').setAttribute('aria-hidden','false');ensureAiGreeting('drawer');if(prompt)sendAi(prompt,'drawer')}
function closeAi(){$('#ai-drawer').classList.remove('open');$('#ai-drawer').setAttribute('aria-hidden','true')}
function ensureAiGreeting(target){const box=target==='page'?$('#ai-page-messages'):$('#ai-drawer-messages');if(box.children.length)return;appendMessage(box,'assistant',state.overview?.top_risks?.length?`Analisei sua postura. Existem ${state.overview.findings.critical||0} riscos críticos e ${state.overview.findings.high||0} altos. Posso explicar o maior risco ou criar um plano de correção.`:'Estou pronta para ajudar. Ainda não há riscos normalizados; posso orientar você a começar pelo inventário de ativos.')}
function appendMessage(box,role,text){const row=document.createElement('div');row.className=`message ${role}`;const bubble=document.createElement('div');bubble.className='message-bubble';bubble.textContent=text;row.appendChild(bubble);box.appendChild(row);box.scrollTop=box.scrollHeight;return bubble}
async function sendAi(message,target='drawer'){
  const box=target==='page'?$('#ai-page-messages'):$('#ai-drawer-messages');ensureAiGreeting(target);appendMessage(box,'user',message);const waiting=appendMessage(box,'assistant','Analisando os dados autorizados...');
  try{const payload={message};if(state.currentFinding)payload.finding_id=state.currentFinding.id;const response=await api('/ai/chat',{method:'POST',body:JSON.stringify(payload)});waiting.textContent=response.summary||'Não há dados suficientes na Iron AI para confirmar isso.';if(response.actions?.length){waiting.textContent+=`\n\n${response.actions.map(item=>`${item.priority}. ${item.action}`).join('\n')}`}if(response.recommendations?.length&&!response.actions?.length){waiting.textContent+=`\n\n${response.recommendations.map((item,index)=>`${index+1}. ${item}`).join('\n')}`}waiting.textContent+=`\n\nFonte: ${response.provider==='groq'?'Groq conectado + dados Iron AI':response.provider==='openrouter'?'OpenRouter conectado + dados Iron AI':'motor determinístico Iron AI'}`}
  catch(error){waiting.textContent=`Não consegui concluir: ${error.message}`}
}

async function proposeCurrentRiskAction(){
  if(!state.currentFinding)return;
  const risk=state.currentFinding;
  try{
    await api('/ai/actions',{method:'POST',body:JSON.stringify({action_type:'create_remediation_task',finding_id:risk.id,title:`Corrigir: ${risk.title}`,description:risk.remediation||risk.description||'Investigar e corrigir o finding com evidências verificáveis.',priority:risk.severity||'medium'})});
    toast('Ação proposta. Um owner ou admin deve aprovar antes da execução.');
    $('#risk-drawer').classList.remove('open');navigate('ai');await loadAiActions();
  }catch(error){toast(error.message,'error')}
}
async function loadAiActions(){
  try{const data=await api('/ai/actions');state.aiActions=data.actions||[];renderAiActions();return true}catch(error){toast(error.message,'error');return false}
}
function renderAiActions(){
  const box=$('#ai-actions-list');if(!box)return;const role=state.bootstrap?.organization?.role;const canControl=['owner','admin'].includes(role);
  box.innerHTML=state.aiActions.length?state.aiActions.map(action=>{const payload=action.payload||{};let controls='';if(canControl&&action.status==='proposed')controls=`<button data-ai-action="approve" data-action-id="${action.id}">Aprovar</button><button class="danger" data-ai-action="reject" data-action-id="${action.id}">Rejeitar</button>`;if(canControl&&action.status==='approved')controls=`<button class="execute" data-ai-action="execute" data-action-id="${action.id}"><i class="fa-solid fa-play"></i> Executar</button><button class="danger" data-ai-action="reject" data-action-id="${action.id}">Rejeitar</button>`;return `<article class="ai-action-item"><div><span class="ai-action-status ${action.status}">${statusLabel(action.status)}</span><h3>${escapeHtml(payload.title||'Tarefa de remediação')}</h3><p>${escapeHtml(payload.description||'Sem descrição.')}</p><small>Finding #${payload.finding_id||'—'} · prioridade ${escapeHtml(payload.priority||'medium')} · ${dateLabel(action.created_at)}</small></div><div class="ai-action-controls">${controls}</div></article>`}).join(''):`<div class="empty-state compact"><p>Nenhuma ação proposta. Abra um risco e escolha “Propor tarefa de correção”.</p></div>`;
}
async function controlAiAction(id,operation,button){if(operation==='execute'&&!await showConfirmDialog({variant:'warning',icon:'fa-play',title:'Executar ação aprovada?',message:'A Iron AI criará uma tarefa real de remediação vinculada a este risco.',details:'A execução fica registrada na trilha de auditoria.',confirmText:'Executar ação',confirmIcon:'fa-play'}))return;setBusy(button,true,'Processando...');try{const result=await api(`/ai/actions/${id}/${operation}`,{method:'POST'});toast(operation==='execute'?`Ação executada: tarefa #${result.remediation_task_id} criada.`:`Ação ${operation==='approve'?'aprovada':'rejeitada'}.`);await Promise.all([loadAiActions(),refreshCore()])}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}

function openModal(selector){$(selector).classList.add('open')}function closeModals(){$$('.modal-backdrop').forEach(el=>el.classList.remove('open'))}
async function addAsset(event){event.preventDefault();const button=event.submitter;setBusy(button,true,'Adicionando...');try{await api('/assets',{method:'POST',body:JSON.stringify({type:$('#asset-type').value,name:$('#asset-name').value.trim(),environment:$('#asset-environment').value,criticality:$('#asset-criticality').value,internet_exposed:$('#asset-exposed').checked})});event.target.reset();closeModals();toast('Ativo adicionado ao inventário.');await refreshCore()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function reconcile(button){setBusy(button,true,'Importando...');try{const result=await api('/findings/reconcile',{method:'POST'});toast(`${result.findings_upserted} findings processados.`);await refreshCore()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}}
async function refreshCore(){await loadCore();renderShell();const loaders=[loadTrend(),loadJobs(),loadReports(),loadIntegrations()];if(state.currentView==='compliance')loaders.push(loadCompliance());if(state.currentView==='ai')loaders.push(loadAiActions());if(state.currentView==='settings')loaders.push(loadRuntimeSettings());const results=await Promise.all(loaders);if(results.some(result=>result===false))throw new Error('Parte dos dados não pôde ser atualizada. Verifique os avisos exibidos.');updateRefreshTimestamp();return true}

function openOnboarding(){state.onboarding.step=1;$('#onboarding').classList.add('open');$('#onboarding').setAttribute('aria-hidden','false');renderOnboarding()}
function renderOnboarding(){const step=state.onboarding.step;$$('.onboarding-step').forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===step));$('#onboarding-progress').style.width=`${Math.min(step,4)*25}%`;$('#onboarding-back').style.visibility=step>1&&step<5?'visible':'hidden';$('#onboarding-next').style.display=step===5?'none':'inline-flex';$('#onboarding-next').innerHTML=step===4?'Criar visão inicial <i class="fa-solid fa-wand-magic-sparkles"></i>':'Continuar <i class="fa-solid fa-arrow-right"></i>'}
function selectChoice(container,button,key){container.querySelectorAll('button').forEach(el=>el.classList.remove('selected'));button.classList.add('selected');state.onboarding[key]=button.dataset.value}
async function onboardingNext(){const s=state.onboarding;if(s.step===1){const domain=$('#onboarding-domain').value.trim().replace(/^https?:\/\//,'').replace(/\/$/,'');if(!domain||!domain.includes('.')){toast('Informe um domínio válido.','error');return}s.domain=domain}else if(s.step===2&&!s.cloud){toast('Selecione uma opção de hospedagem.','error');return}else if(s.step===4&&!s.employees){toast('Selecione o tamanho da empresa.','error');return}if(s.step<4){s.step++;renderOnboarding();return}s.step=5;renderOnboarding();try{const asset=await api('/assets',{method:'POST',body:JSON.stringify({type:'domain',name:s.domain,hostname:s.domain,url:`https://${s.domain}`,environment:'production',criticality:'high',internet_exposed:true,metadata:{cloud_provider:s.cloud,employees:s.employees,onboarding:true}})});const job=await api('/scan-jobs',{method:'POST',body:JSON.stringify({job_type:'web_security_scan',asset_id:asset.id})});$('#onboarding').classList.remove('open');if(s.github==='yes'){navigate('integrations');openModal('#github-modal')}else navigate('monitoring');await refreshCore();toast('Ativo criado. O primeiro scan real está em execução.');pollJob(job.id)}catch(error){s.step=4;renderOnboarding();toast(error.message,'error')}}
function onboardingBack(){if(state.onboarding.step>1){state.onboarding.step--;renderOnboarding()}}

function closeMobile(){$('#sidebar').classList.remove('open');$('#mobile-overlay').classList.remove('open')}
function bindEvents(){
  $$('.nav-item').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.view)));$$('[data-view-target]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.viewTarget)));$$('[data-open-ai]').forEach(button=>button.addEventListener('click',()=>openAi()));$$('[data-open-asset]').forEach(button=>button.addEventListener('click',()=>openModal('#asset-modal')));$$('[data-close-modal]').forEach(button=>button.addEventListener('click',closeModals));$$('.modal-backdrop').forEach(el=>el.addEventListener('click',event=>{if(event.target===el)closeModals()}));
  $('#logout-button').addEventListener('click',async()=>{if(!await showConfirmDialog({variant:'info',icon:'fa-arrow-right-from-bracket',kicker:'Encerrar acesso',title:'Sair da Iron AI?',message:'Sua sessão neste dispositivo será encerrada com segurança.',details:false,confirmText:'Sim, sair',confirmIcon:'fa-arrow-right-from-bracket'}))return;window.showTransitionLoading?.('Encerrando sessão...','Protegendo seus dados antes de sair.');try{await api('/auth/logout',{method:'POST'})}catch(_){}clearSession();location.href='/index.html'});$('#refresh-button').addEventListener('click',async event=>{const button=event.currentTarget;const icon=button.querySelector('i');button.disabled=true;button.setAttribute('aria-busy','true');icon.classList.add('fa-spin');try{await refreshCore();toast(`Dados reais atualizados às ${state.lastRefreshAt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}.`)}catch(error){toast(error.message,'error')}finally{icon.classList.remove('fa-spin');button.disabled=false;button.removeAttribute('aria-busy')}});$('#notifications-button').addEventListener('click',()=>{navigate('overview');setTimeout(()=>$('.timeline-panel')?.scrollIntoView({behavior:'smooth',block:'center'}),100)});$('#org-button').addEventListener('click',()=>toast(`Organização ativa: ${state.bootstrap.organization.name}`));$$('[data-settings-tab]').forEach(button=>button.addEventListener('click',()=>selectSettingsTab(button.dataset.settingsTab)));
  $('#mobile-menu').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#mobile-overlay').classList.add('open')});$('#mobile-overlay').addEventListener('click',closeMobile);$('#asset-form').addEventListener('submit',addAsset);$('#asset-search').addEventListener('input',renderAssets);$('#asset-environment-filter').addEventListener('change',renderAssets);$('#scan-asset-button').addEventListener('click',()=>openScanModal());$('#quick-scan-button').addEventListener('click',()=>openScanModal());$('#scan-form').addEventListener('submit',startWebScan);$('#scan-authenticated').addEventListener('change',event=>{$('#scan-auth-fields').hidden=!event.target.checked});$('#scan-auth-type').addEventListener('change',event=>{$('#scan-header-label').hidden=event.target.value!=='api_key'});$('#assets-table').addEventListener('click',event=>{const button=event.target.closest('[data-scan-asset]');if(button){event.stopPropagation();openScanModal(Number(button.dataset.scanAsset))}});
  $$('.filter-chip').forEach(button=>button.addEventListener('click',()=>{$$('.filter-chip').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderRisks()}));$('#risk-status-filter').addEventListener('change',renderRisks);$('#risks-table').addEventListener('click',event=>{const row=event.target.closest('[data-risk-id]');if(row)openRisk(Number(row.dataset.riskId))});$('#overview-risks').addEventListener('click',event=>{const row=event.target.closest('[data-risk-id]');if(row)openRisk(Number(row.dataset.riskId))});$('#close-risk').addEventListener('click',()=>{$('#risk-drawer').classList.remove('open');state.currentFinding=null});$('#risk-detail').addEventListener('click',event=>{const status=event.target.closest('[data-set-risk-status]')?.dataset.setRiskStatus;if(status)setRiskStatus(status);if(event.target.closest('[data-ask-current-risk]'))openAi('Explique este risco e diga exatamente o que devo fazer.');if(event.target.closest('[data-propose-current-risk]'))proposeCurrentRiskAction();if(event.target.closest('[data-create-jira-issue]'))createJiraIssue()});
  $('#reconcile-button').addEventListener('click',event=>reconcile(event.currentTarget));$('#risks-reconcile-button').addEventListener('click',event=>reconcile(event.currentTarget));$('#trend-period').addEventListener('change',loadTrend);$('#snapshot-button')?.addEventListener('click',createSnapshot);$('#refresh-jobs').addEventListener('click',event=>refreshJobs(event.currentTarget));$$('[data-generate-report]').forEach(button=>button.addEventListener('click',()=>generateReport(button.dataset.generateReport,button)));$('#reports-list').addEventListener('click',event=>{const link=event.target.closest('[data-download-report]');if(link){event.preventDefault();downloadReport(link.dataset.downloadReport)}});
  $('#configure-sensor-button').addEventListener('click',openSensorConfiguration);$('#configure-waf-button').addEventListener('click',()=>openModal('#waf-modal'));$('#refresh-security-events').addEventListener('click',loadSecurityMonitoring);$('#sensor-form').addEventListener('submit',createSecuritySensor);$('#waf-form').addEventListener('submit',connectCloudflareWaf);$('#copy-sensor-key').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#sensor-secret').textContent);toast('Chave do sensor copiada.')}catch(_){toast('Selecione e copie a chave manualmente.','error')}});$('#security-sensors-list').addEventListener('click',event=>{const button=event.target.closest('[data-revoke-security-sensor]');if(button)revokeSecuritySensor(button.dataset.revokeSecuritySensor,button)});$('#security-events-list').addEventListener('click',event=>{const contain=event.target.closest('[data-contain-event]');const release=event.target.closest('[data-release-containment]');const resolve=event.target.closest('[data-resolve-security-event]');const ask=event.target.closest('[data-security-ai]');if(contain)containSecurityEvent(contain.dataset.containEvent,contain);if(release)releaseContainment(release.dataset.releaseContainment,release);if(resolve)resolveSecurityEvent(resolve.dataset.resolveSecurityEvent,resolve);if(event.target.closest('[data-open-waf]'))openModal('#waf-modal');if(ask){const incident=state.securityEvents.find(item=>String(item.id)===ask.dataset.securityAi);openAi(`Analise este incidente em tempo real e detalhe contenção, investigação e correção: ${incident?.title||''}. Origem: ${incident?.source_ip||'não informada'}. Evidência: ${incident?.description||''}`)}});
  $$('[data-integration-action]').forEach(button=>button.addEventListener('click',()=>integrationAction(button.dataset.integrationAction,button)));$('#github-form').addEventListener('submit',connectGithub);$('#gitlab-form').addEventListener('submit',connectGitLab);$('#azure-devops-form').addEventListener('submit',connectAzureDevOps);$('#jira-form').addEventListener('submit',connectJira);$('#organization-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;setBusy(button,true,'Salvando...');try{await api('/organization',{method:'PATCH',body:JSON.stringify({name:$('#settings-org-name').value})});toast('Organização atualizada.');await refreshCore()}catch(error){toast(error.message,'error')}finally{setBusy(button,false)}});
  $('#pipeline-key-form').addEventListener('submit',createPipelineKey);$('#copy-pipeline-key').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#pipeline-key-secret').textContent);toast('Chave copiada.')}catch(_){toast('Selecione e copie a chave manualmente.','error')}});$('#pipeline-keys-list').addEventListener('click',event=>{const button=event.target.closest('[data-revoke-pipeline-key]');if(button)revokePipelineKey(button.dataset.revokePipelineKey,button)});$('#refresh-compliance').addEventListener('click',loadCompliance);$('#compliance-controls').addEventListener('click',event=>{const button=event.target.closest('[data-save-compliance]');if(button)saveCompliance(button)});$('#sso-config-form').addEventListener('submit',saveSSOConfig);$('#download-audit-export').addEventListener('click',downloadAuditExport);
  $('#close-ai').addEventListener('click',closeAi);$$('[data-ai-prompt]').forEach(button=>button.addEventListener('click',()=>{const target=state.currentView==='ai'?'page':'drawer';if(target==='drawer')openAi();sendAi(button.dataset.aiPrompt,target)}));$('#ai-drawer-form').addEventListener('submit',event=>{event.preventDefault();const input=$('#ai-drawer-input');if(input.value.trim()){sendAi(input.value.trim(),'drawer');input.value=''}});$('#ai-page-form').addEventListener('submit',event=>{event.preventDefault();const input=$('#ai-page-input');if(input.value.trim()){sendAi(input.value.trim(),'page');input.value=''}});$('#refresh-ai-actions').addEventListener('click',loadAiActions);$('#ai-actions-list').addEventListener('click',event=>{const button=event.target.closest('[data-ai-action]');if(button)controlAiAction(button.dataset.actionId,button.dataset.aiAction,button)});
  $('#onboarding-next').addEventListener('click',onboardingNext);$('#onboarding-back').addEventListener('click',onboardingBack);$('#skip-onboarding').addEventListener('click',()=>{sessionStorage.setItem('onboarding_skipped','1');$('#onboarding').classList.remove('open')});$('#cloud-choices').addEventListener('click',e=>{const b=e.target.closest('button');if(b)selectChoice($('#cloud-choices'),b,'cloud')});$('#github-choices').addEventListener('click',e=>{const b=e.target.closest('button');if(b)selectChoice($('#github-choices'),b,'github')});$('#employee-choices').addEventListener('click',e=>{const b=e.target.closest('button');if(b)selectChoice($('#employee-choices'),b,'employees')});
  $('#restart-onboarding').addEventListener('click',()=>{sessionStorage.removeItem('onboarding_skipped');state.onboarding={step:1,domain:'',cloud:'',github:'later',employees:''};$('#onboarding-domain').value='';$$('.choice-grid button').forEach(button=>button.classList.remove('selected'));openOnboarding()});
  $('#cancel-subscription-button').addEventListener('click',openCancelSubscription);$('#close-cancel-subscription').addEventListener('click',closeCancelSubscription);$('#cancel-subscription-confirmation').addEventListener('input',validateCancellationConfirmation);$('#confirm-cancel-subscription').addEventListener('click',cancelActiveSubscription);
  window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'overview'));document.addEventListener('visibilitychange',syncMonitoringPolling);window.addEventListener('beforeunload',()=>{if(state.monitoringTimer)clearInterval(state.monitoringTimer)});document.addEventListener('click',event=>{if(event.target.closest('#mfa-setup-button'))setupOrDisableMfa();if(event.target.closest('#mfa-confirm-button'))confirmMfa()});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeAi();closeModals();$('#risk-drawer').classList.remove('open')}});
}

document.addEventListener('DOMContentLoaded',()=>{const requested=location.hash.slice(1);if(labels[requested])state.currentView=requested;initialize().then(()=>navigate(state.currentView))});
